### PR TITLE
updating plotly function to show timeseries

### PR DESCRIPTION
**Pull request by Saksham20**
update `show_index_timeseries_plotly()` and its usage in `SingleTracePlotlyWidget `and `SeparateTracesPlotlyWidget`

### CODE REVIEW

**Comment by Saksham20** [comment]
correctly showing behavior time series with this new change to `show_index_timeseries_plotly()`
separatetraces

**Comment by bendichter** [comment]
@Saksham20 This looks good! Nice job with the tests and the gif. One thing: sometimes it is useful to be able to input the index instead of the time. Could you change this so that it is able to take as input either indices or times (but not both)?

**Comment by bendichter** [comment]
Then could you add tests for inputting index and a test making sure that inputting both raises a value error

**Review by bendichter — CHANGES_REQUESTED** [review]
see above

**Review by bendichter — APPROVED** [review]

**Pull request merged**
