### PR TITLE
Brunton brains

### PR DESCRIPTION
**Pull request by MRScheid**
Here is a screenshot of the widget currently: 

image

### CODE REVIEW

**Comment by MRScheid** [comment]
For some reason whenever I toggle the new "Color by:" radio button, the handler is called twice.  I can't figure out why this is.

**Comment by bendichter** [comment]
Could you make coloring by electrode group a 3rd option? Also ideally the additional options would be automatically determined by the columns of the electrodes table. That would make this generalize to other groups

**Comment by MRScheid** [comment]
> 
> 
> Could you make coloring by electrode group a 3rd option? Also ideally the additional options would be automatically determined by the columns of the electrodes table. That would make this generalize to other groups


@bendichter took care of this in the last commit.  Here's a screenshot of the current layout:
image

**Comment by bendichter** [comment]
Awesome! Could you have the program automatically determine whether the column is continuous or categorical and only show the colorbar if it is continuous? Also, could you use a colormap other than jet?

**Comment by MRScheid** [comment]
image

Done and done.  Using viridis now.

**Comment by bendichter** [comment]
Looks good! Can you add a test?

**Review by bendichter — APPROVED** [review]

**Pull request merged**
