### PR TITLE
adding 2p plotly traces

### PR DESCRIPTION
**Pull request by Saksham20**
adds a plotly widget to viz the 2photon series images

### CODE REVIEW

**Comment by bendichter** [comment]
Can you add a screenshot?

**Comment by Saksham20** [comment]
> Can you add a screenshot?

2pseries

**Comment by bendichter** [comment]
Is this a real dataset? The image doesn't look like a microscopy image

**Comment by Saksham20** [comment]
> Is this a real dataset? The image doesn't look like a microscopy image

its a dataset containing first 10 frames of an .sbx file

**Comment by bendichter** [comment]
Are you sure it's read correctly? The data doesn't look like I would expect

**Comment by Saksham20** [comment]
https://github.com/catalystneuro/roiextractors/pull/78

**Comment by Saksham20** [comment]
This change handles the correct reordering of ImageSeries/Images in nwbfiles. PR: https://github.com/catalystneuro/roiextractors/pull/79
 THe expected dim of image is` (x,y)` according to nwb documentation [here](https://pynwb.readthedocs.io/en/stable/pynwb.image.html#module-pynwb.image)
Below is how it looks after both changes: 
finalorder_changes_both

**Pull request merged**
